Expandable list and table - Added Helper methods.
helsingborg-stad/modularity-json-render pull request #4
Opened 2020-12-10 18:27 UTC by silvergrund

Expandable list view with logic fixed
Expandable table view with logic fixed
Table headers align with expandable content
Layout Overhaul to go with styleguide
Translation

2020-12-15 13:00 UTC, Muckbuck requested changes

2020-12-15 16:26 UTC, silvergrund commented on source/js/Front/Components/Accordion.js
> +            <header className="c-accordion__button-wrapper">
Should be resolved...

2020-12-15 16:26 UTC, silvergrund commented on source/js/Front/Components/Accordion.js
> +            <SearchField
Should be resolved...

2020-12-15 16:27 UTC, silvergrund commented on source/js/Front/Components/Accordion.js
> +                    <span key={i}
Should be resolved...

2020-12-15 16:27 UTC, silvergrund commented on source/js/Front/Components/Accordion.js
> +                    index={index + '-' + Math.round(Math.random() * 100000000)}
Should be resolved...

2020-12-18 14:02 UTC, alexanderbomanskoug2 requested changes

2020-12-18 14:02 UTC, alexanderbomanskoug2 commented on source/js/Front/Components/AccordionItem.js
> -                    <span key={i} className="column-header" dangerouslySetInnerHTML={{__html: title}} />
Key is not unique

2020-12-18 14:02 UTC, alexanderbomanskoug2 commented on source/js/Front/Components/AccordionItem.js
> +                        <span key={i}
Key is not unique

2020-12-18 14:02 UTC, alexanderbomanskoug2 commented on source/js/Front/Components/AccordionItem.js
> +                <p key={i} className="u-mb-2">
Key is not unique

2020-12-18 14:02 UTC, alexanderbomanskoug2 commented on source/js/Front/Components/Table.js
> +                        <th class="c-table__column" key={i}>
Key is not unique

2020-12-18 14:02 UTC, alexanderbomanskoug2 commented on source/js/Front/Components/Table.js
> +                            <td class="c-table__column" key={i} dangerouslySetInnerHTML={{__html: heading}} />
Key is not unique

2020-12-18 14:07 UTC, alexanderbomanskoug2 commented
Changes requested but not required, otherwise approved

2020-12-18 14:42 UTC, silvergrund reviewed
> Changes requested but not required, otherwise approved

Out of scope - Not a refactor commit

2020-12-22 10:55 UTC, merged